/* Generated by Cython 0.29.32 */

#ifndef __PYX_HAVE__prolothar_ca__model__sat__variable
#define __PYX_HAVE__prolothar_ca__model__sat__variable

#include "Python.h"

#ifndef __PYX_HAVE_API__prolothar_ca__model__sat__variable

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int __pyx_v_12prolothar_ca_5model_3sat_8variable_UNKNOWN;
__PYX_EXTERN_C int __pyx_v_12prolothar_ca_5model_3sat_8variable_TRUE;
__PYX_EXTERN_C int __pyx_v_12prolothar_ca_5model_3sat_8variable_FALSE;

#endif /* !__PYX_HAVE_API__prolothar_ca__model__sat__variable */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initvariable(void);
#else
PyMODINIT_FUNC PyInit_variable(void);
#endif

#endif /* !__PYX_HAVE__prolothar_ca__model__sat__variable */
